name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "assets/**"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $is_release ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-win-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true
      - name: Download MFA
        uses: robinraju/release-downloader@v1
        if: matrix.arch == 'x86_64'
        with:
          repository: SweetSmellFox/MFAWPF
          fileName: "MFAWPF-*"

          latest: true
          out-file-path: "MFA"
          extract: true
        
      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}
          
      - name: Install MFA
        if: matrix.arch == 'x86_64'
        shell: bash
        run: |
          cp ./MFA/MFAWPF.exe ./install/MFAWPF.exe
        
      - uses: actions/upload-artifact@v4
        with:
          name: MaaXXX-win-${{ matrix.arch }}
          path: "install"

      - name: Download MFW
        uses: robinraju/release-downloader@v1
        if: matrix.arch == 'x86_64'
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-win-x86_64*"
          latest: true
          out-file-path: "MFW"
          extract: true

      - name: Install MFW
        if: matrix.arch == 'x86_64'
        shell: bash
        run: |
          rm MFW/MFW-PyQt6-win-x86_64* 
          python ./deploy.py

      - uses: actions/upload-artifact@v4
        if: matrix.arch == 'x86_64'
        with:
          name: MaaXXX-win-${{ matrix.arch }}-MFW-PyQt
          path: "MFW"

  ubuntu:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-linux-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}

      - uses: actions/upload-artifact@v4
        with:
          name: MaaXXX-linux-${{ matrix.arch }}
          path: "install"

      - name: Download MFW
        uses: robinraju/release-downloader@v1
        if: matrix.arch == 'x86_64'
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-linux-x86_64*"
          latest: true
          out-file-path: "MFW"
          extract: true

      - name: Install MFW
        if: matrix.arch == 'x86_64'
        shell: bash
        run: |
          rm MFW/MFW-PyQt6-linux-x86_64* 
          python ./deploy.py

      - uses: actions/upload-artifact@v4
        if: matrix.arch == 'x86_64'
        with:
          name: MaaXXX-linux-${{ matrix.arch }}-MFW-PyQt
          path: "MFW"

  macos:
    needs: meta
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Download MaaFramework
        uses: robinraju/release-downloader@v1
        with:
          repository: MaaXYZ/MaaFramework
          fileName: "MAA-macos-${{ matrix.arch }}*"
          latest: true
          out-file-path: "deps"
          extract: true

      - name: Install
        shell: bash
        run: |
          python ./install.py ${{ needs.meta.outputs.tag }}

      - uses: actions/upload-artifact@v4
        with:
          name: MaaXXX-macos-${{ matrix.arch }}
          path: "install"

      - name: Download MFW
        uses: robinraju/release-downloader@v1
        if: matrix.arch == 'x86_64'
        with:
          repository: overflow65537/MFW-PyQt6
          fileName: "MFW-PyQt6-macos-x86_64*"
          latest: true
          out-file-path: "MFW"
          extract: true

      - name: Install MFW
        if: matrix.arch == 'x86_64'
        shell: bash
        run: |
          rm MFW/MFW-PyQt6-macos-x86_64*
          python ./deploy.py

      - uses: actions/upload-artifact@v4
        if: matrix.arch == 'x86_64'
        with:
          name: MaaXXX-macos-${{ matrix.arch }}-MFW-PyQt
          path: "MFW"

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows, ubuntu, macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}
