name: install

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "**.py"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/install.yml"
      - "**.py"
  workflow_dispatch:

jobs:
  meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set_tag
        run: |
          is_release=${{ startsWith(github.ref, 'refs/tags/v') }}
          tag=$(git describe --tags --match "v*" ${{ github.ref }} || true)
          if [[ $tag != v* ]]; then
            tag=$(curl -sX GET "https://api.github.com/repos/${{ github.repository }}/releases/latest" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | awk '/tag_name/{print $4}' FS='["]')
            if [[ $tag != v* ]]; then
              tag="v0.0.0"
            fi
            tag=$(date "+$tag-%y%m%d-$(git rev-parse --short HEAD)")
          fi
          if ! $($is_release) ; then
            prefix=${tag%-*-*}
            suffix=${tag#$prefix-}
            tag="$prefix-ci.$suffix"
          fi

          echo tag=$tag | tee -a $GITHUB_OUTPUT
          echo is_release=$is_release | tee -a $GITHUB_OUTPUT
    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      is_release: ${{ steps.set_tag.outputs.is_release }}

  windows:
    needs: meta
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

    - name: Set up Python
        uses: actions/setup-python@v2
        with:
        python-version: '3.12'

    - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r ./requirements.txt
        pip install -r ./requirementstemp.txt

      - name: Install
        shell: bash
        run: |
          python ./bulid.py

      - uses: actions/upload-artifact@v4
        with:
          name: MFW-PyQt6-win-${{ matrix.arch }}
          path: "dist.main"

  ubuntu:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Set up Python
          uses: actions/setup-python@v2
          with:
          python-version: '3.10'
  
      - name: Install dependencies
          run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r ./requirements.txt
          pip install -r ./requirementstemp.txt

      - name: Install
        shell: bash
        run: |
          python ./bulid.py

      - uses: actions/upload-artifact@v4
        with:
          name: MFW-PyQt6-linux-${{ matrix.arch }}
          path: "dist.main"

  macos:
    needs: meta
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
          uses: actions/setup-python@v2
          with:
          python-version: '3.10'
  
      - name: Install dependencies
          run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r ./requirements.txt
          pip install -r ./requirementstemp.txt


      - name: Install
        shell: bash
        run: |
          python ./bulid.py

      - uses: actions/upload-artifact@v4
        with:
          name: MFW-PyQt6-macos-${{ matrix.arch }}
          path: "dist.main"

  release:
    if: ${{ needs.meta.outputs.is_release == 'true' }}
    needs: [meta, windows, ubuntu, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: assets

      - run: |
          cd assets
          for f in *; do
            (cd $f && zip -r ../$f-${{ needs.meta.outputs.tag }}.zip .)
          done
      - uses: softprops/action-gh-release@v2
        with:
          files: assets/*
          tag_name: ${{ needs.meta.outputs.tag }}